<?php

declare(strict_types=1);

namespace SchemaLens\Migration;

use SchemaLens\DTO\ComparisonResult;
use SchemaLens\Sql\SqlGenerator;

/**
 * Generates a Laravel migration file that attempts to sync B → A.
 * Does NOT run the migration.
 */
final class MigrationGenerator
{
    public function __construct(
        private readonly SqlGenerator $sqlGenerator = new SqlGenerator,
    ) {}

    /**
     * @return string Absolute path to the generated migration file
     */
    public function generate(ComparisonResult $result, ?string $path = null): string
    {
        $path ??= database_path('migrations');
        $timestamp = date('Y_m_d_His');
        $from = $this->safeName($result->from->connection);
        $to = $this->safeName($result->to->connection);
        $filename = "{$timestamp}_schema_lens_sync_{$from}_to_{$to}.php";
        $fullPath = rtrim($path, DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR.$filename;

        $statements = $this->sqlGenerator->generate($result);
        $body = $this->buildMigrationBody($statements, $result);

        if (! is_dir($path) && ! mkdir($path, 0755, true) && ! is_dir($path)) {
            throw new \RuntimeException('Unable to create migrations directory: '.$path);
        }

        if (file_put_contents($fullPath, $body) === false) {
            throw new \RuntimeException('Unable to write migration file: '.$fullPath);
        }

        return $fullPath;
    }

    /**
     * @param  list<\SchemaLens\DTO\SqlStatement>  $statements
     */
    private function buildMigrationBody(array $statements, ComparisonResult $result): string
    {
        $upStatements = [];

        if ($statements === []) {
            $upStatements[] = "        // No schema differences detected between {$result->from->connection} and {$result->to->connection}.";
        } else {
            foreach ($statements as $statement) {
                $comment = $statement->destructive
                    ? '        // ⚠ DESTRUCTIVE: '.$statement->description
                    : '        // '.$statement->description;

                $escaped = addcslashes($statement->sql, "\\'");
                $upStatements[] = $comment;
                $upStatements[] = "        DB::statement('{$escaped}');";
                $upStatements[] = '';
            }
        }

        $upBody = implode("\n", $upStatements);

        return <<<PHP
<?php

declare(strict_types=1);

/*
 * Generated by SchemaLens.
 *
 * Review this migration carefully before execution.
 *
 * SchemaLens does not automatically execute generated migrations.
 *
 * Source (desired): {$result->from->connection}
 * Target (to update): {$result->to->connection}
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * Attempts to make the target database match the source schema.
     * Some differences may require manual review or raw SQL adjustments.
     */
    public function up(): void
    {
{$upBody}
    }

    /**
     * Reverse the migrations.
     *
     * Automatic rollback is not generated — SchemaLens comparisons are directional.
     */
    public function down(): void
    {
        // SchemaLens does not generate automatic down() migrations.
        // Capture a reverse comparison if you need rollback SQL.
    }
};

PHP;
    }

    private function safeName(string $name): string
    {
        return preg_replace('/[^a-zA-Z0-9_]+/', '_', $name) ?? 'connection';
    }
}
