<?php

declare(strict_types=1);

namespace SchemaLens\Sql;

use SchemaLens\Contracts\SqlGeneratorInterface;
use SchemaLens\DTO\ColumnSchema;
use SchemaLens\DTO\ComparisonResult;
use SchemaLens\DTO\ForeignKeySchema;
use SchemaLens\DTO\IndexSchema;
use SchemaLens\DTO\SchemaDifference;
use SchemaLens\DTO\SqlStatement;
use SchemaLens\DTO\TableSchema;
use SchemaLens\Enums\DifferenceType;
use SchemaLens\Enums\IndexType;

/**
 * Generates deterministic SQL to make database B (to) match database A (from).
 * SQL is NEVER executed automatically.
 */
final class SqlGenerator implements SqlGeneratorInterface
{
    /**
     * {@inheritdoc}
     */
    public function generate(ComparisonResult $result): array
    {
        $statements = [];

        // Order matters for applying changes safely:
        // 1. Create missing tables
        // 2. Drop extra FKs / indexes / columns (destructive)
        // 3. Add/modify columns
        // 4. Add indexes / FKs
        // 5. Drop extra tables (destructive, last)

        foreach ($result->differences as $diff) {
            $generated = match ($diff->type) {
                DifferenceType::TableRemoved => $this->createTable($diff),
                DifferenceType::TableAdded => $this->dropTable($diff),
                DifferenceType::TableModified => $this->alterTableOptions($diff),
                DifferenceType::ColumnRemoved => $this->addColumn($diff),
                DifferenceType::ColumnAdded => $this->dropColumn($diff),
                DifferenceType::ColumnModified => $this->modifyColumn($diff),
                DifferenceType::IndexRemoved => $this->addIndex($diff),
                DifferenceType::IndexAdded => $this->dropIndex($diff),
                DifferenceType::IndexModified => $this->modifyIndex($diff),
                DifferenceType::ForeignKeyRemoved => $this->addForeignKey($diff),
                DifferenceType::ForeignKeyAdded => $this->dropForeignKey($diff),
                DifferenceType::ForeignKeyModified => $this->modifyForeignKey($diff),
            };

            foreach ($generated as $stmt) {
                $statements[] = $stmt;
            }
        }

        return $this->orderStatements($statements);
    }

    public function toSqlString(ComparisonResult $result): string
    {
        $statements = $this->generate($result);

        if ($statements === []) {
            return "-- SchemaLens: no differences detected.\n-- Databases are in sync.\n";
        }

        $lines = [
            '-- Generated by SchemaLens',
            '-- See exactly what changed in your database.',
            '--',
            '-- This SQL is intended to make "'.$result->to->connection.'" match "'.$result->from->connection.'".',
            '-- SchemaLens does NOT execute this SQL automatically.',
            '-- Review carefully before running, especially destructive statements.',
            '',
        ];

        $hasDestructive = false;

        foreach ($statements as $statement) {
            if ($statement->destructive) {
                $hasDestructive = true;
                $lines[] = '-- ⚠ DESTRUCTIVE: '.$statement->description;
            } elseif ($statement->description !== '') {
                $lines[] = '-- '.$statement->description;
            }

            $lines[] = $statement->sql.';';
            $lines[] = '';
        }

        if ($hasDestructive) {
            array_splice($lines, 6, 0, [
                '-- ⚠ WARNING: This script contains destructive operations',
                '-- (DROP TABLE / DROP COLUMN / DROP INDEX / DROP CONSTRAINT).',
                '-- These may permanently remove data or database objects.',
                '',
            ]);
        }

        return implode("\n", $lines);
    }

    /**
     * @return list<SqlStatement>
     */
    private function createTable(SchemaDifference $diff): array
    {
        if ($diff->from === null) {
            return [];
        }

        $table = $this->hydrateTable($diff->from);
        $sql = $this->buildCreateTableSql($table);

        return [
            new SqlStatement(
                sql: $sql,
                destructive: false,
                description: "Create missing table `{$table->name}`",
                table: $table->name,
            ),
        ];
    }

    /**
     * @return list<SqlStatement>
     */
    private function dropTable(SchemaDifference $diff): array
    {
        $name = $diff->table;

        return [
            new SqlStatement(
                sql: 'DROP TABLE IF EXISTS '.$this->quote($name),
                destructive: true,
                description: "Drop extra table `{$name}`",
                table: $name,
            ),
        ];
    }

    /**
     * @return list<SqlStatement>
     */
    private function alterTableOptions(SchemaDifference $diff): array
    {
        $parts = [];
        $from = $diff->from ?? [];
        $to = $diff->to ?? [];

        if (($from['engine'] ?? null) !== null && ($from['engine'] ?? null) !== ($to['engine'] ?? null)) {
            $parts[] = 'ENGINE='.$from['engine'];
        }

        if (($from['collation'] ?? null) !== null && ($from['collation'] ?? null) !== ($to['collation'] ?? null)) {
            $charset = $from['charset'] ?? null;
            if ($charset) {
                $parts[] = 'DEFAULT CHARSET='.$charset;
            }
            $parts[] = 'COLLATE='.$from['collation'];
        }

        if (($from['comment'] ?? '') !== ($to['comment'] ?? '')) {
            $parts[] = 'COMMENT='.$this->quoteString((string) ($from['comment'] ?? ''));
        }

        if ($parts === []) {
            return [];
        }

        return [
            new SqlStatement(
                sql: 'ALTER TABLE '.$this->quote($diff->table).' '.implode(' ', $parts),
                destructive: false,
                description: "Update table options for `{$diff->table}`",
                table: $diff->table,
            ),
        ];
    }

    /**
     * @return list<SqlStatement>
     */
    private function addColumn(SchemaDifference $diff): array
    {
        if ($diff->from === null) {
            return [];
        }

        $def = $this->columnDefinitionFromArray($diff->from);

        return [
            new SqlStatement(
                sql: 'ALTER TABLE '.$this->quote($diff->table).' ADD COLUMN '.$def,
                destructive: false,
                description: "Add missing column `{$diff->table}`.`{$diff->object}`",
                table: $diff->table,
            ),
        ];
    }

    /**
     * @return list<SqlStatement>
     */
    private function dropColumn(SchemaDifference $diff): array
    {
        return [
            new SqlStatement(
                sql: 'ALTER TABLE '.$this->quote($diff->table).' DROP COLUMN '.$this->quote($diff->object),
                destructive: true,
                description: "Drop extra column `{$diff->table}`.`{$diff->object}`",
                table: $diff->table,
            ),
        ];
    }

    /**
     * @return list<SqlStatement>
     */
    private function modifyColumn(SchemaDifference $diff): array
    {
        if ($diff->from === null) {
            return [];
        }

        $def = $this->columnDefinitionFromArray($diff->from);

        return [
            new SqlStatement(
                sql: 'ALTER TABLE '.$this->quote($diff->table).' MODIFY COLUMN '.$def,
                destructive: false,
                description: "Modify column `{$diff->table}`.`{$diff->object}` to match source",
                table: $diff->table,
            ),
        ];
    }

    /**
     * @return list<SqlStatement>
     */
    private function addIndex(SchemaDifference $diff): array
    {
        if ($diff->from === null) {
            return [];
        }

        $index = $this->hydrateIndex($diff->from);

        return [
            new SqlStatement(
                sql: $this->buildAddIndexSql($diff->table, $index),
                destructive: false,
                description: "Add missing index `{$index->name}` on `{$diff->table}`",
                table: $diff->table,
            ),
        ];
    }

    /**
     * @return list<SqlStatement>
     */
    private function dropIndex(SchemaDifference $diff): array
    {
        $name = $diff->object;

        if (strtoupper($name) === 'PRIMARY') {
            $sql = 'ALTER TABLE '.$this->quote($diff->table).' DROP PRIMARY KEY';
        } else {
            $sql = 'ALTER TABLE '.$this->quote($diff->table).' DROP INDEX '.$this->quote($name);
        }

        return [
            new SqlStatement(
                sql: $sql,
                destructive: true,
                description: "Drop extra index `{$name}` on `{$diff->table}`",
                table: $diff->table,
            ),
        ];
    }

    /**
     * @return list<SqlStatement>
     */
    private function modifyIndex(SchemaDifference $diff): array
    {
        return array_merge(
            $this->dropIndex(new SchemaDifference(
                type: DifferenceType::IndexAdded,
                severity: $diff->severity,
                table: $diff->table,
                object: $diff->object,
                from: null,
                to: $diff->to,
                message: $diff->message,
                destructive: true,
            )),
            $this->addIndex(new SchemaDifference(
                type: DifferenceType::IndexRemoved,
                severity: $diff->severity,
                table: $diff->table,
                object: $diff->object,
                from: $diff->from,
                to: null,
                message: $diff->message,
            )),
        );
    }

    /**
     * @return list<SqlStatement>
     */
    private function addForeignKey(SchemaDifference $diff): array
    {
        if ($diff->from === null) {
            return [];
        }

        $fk = $this->hydrateForeignKey($diff->from);

        return [
            new SqlStatement(
                sql: $this->buildAddForeignKeySql($diff->table, $fk),
                destructive: false,
                description: "Add missing foreign key `{$fk->name}` on `{$diff->table}`",
                table: $diff->table,
            ),
        ];
    }

    /**
     * @return list<SqlStatement>
     */
    private function dropForeignKey(SchemaDifference $diff): array
    {
        return [
            new SqlStatement(
                sql: 'ALTER TABLE '.$this->quote($diff->table).' DROP FOREIGN KEY '.$this->quote($diff->object),
                destructive: true,
                description: "Drop extra foreign key `{$diff->object}` on `{$diff->table}`",
                table: $diff->table,
            ),
        ];
    }

    /**
     * @return list<SqlStatement>
     */
    private function modifyForeignKey(SchemaDifference $diff): array
    {
        return array_merge(
            $this->dropForeignKey(new SchemaDifference(
                type: DifferenceType::ForeignKeyAdded,
                severity: $diff->severity,
                table: $diff->table,
                object: $diff->object,
                from: null,
                to: $diff->to,
                message: $diff->message,
                destructive: true,
            )),
            $this->addForeignKey(new SchemaDifference(
                type: DifferenceType::ForeignKeyRemoved,
                severity: $diff->severity,
                table: $diff->table,
                object: $diff->object,
                from: $diff->from,
                to: null,
                message: $diff->message,
            )),
        );
    }

    private function buildCreateTableSql(TableSchema $table): string
    {
        $lines = [];

        foreach ($table->columns as $column) {
            $lines[] = '  '.$this->columnDefinition($column);
        }

        foreach ($table->indexes as $index) {
            if ($index->type === IndexType::Primary) {
                $cols = implode(', ', array_map(fn ($c) => $this->quote($c), $index->columns));
                $lines[] = '  PRIMARY KEY ('.$cols.')';
            } else {
                $lines[] = '  '.$this->indexInlineDefinition($index);
            }
        }

        // FKs can be added in CREATE or separately; include inline for completeness
        foreach ($table->foreignKeys as $fk) {
            $lines[] = '  '.$this->foreignKeyInlineDefinition($fk);
        }

        $sql = 'CREATE TABLE '.$this->quote($table->name)." (\n".implode(",\n", $lines)."\n)";

        $options = [];
        if ($table->engine) {
            $options[] = 'ENGINE='.$table->engine;
        }
        if ($table->charset) {
            $options[] = 'DEFAULT CHARSET='.$table->charset;
        }
        if ($table->collation) {
            $options[] = 'COLLATE='.$table->collation;
        }
        if ($table->comment) {
            $options[] = 'COMMENT='.$this->quoteString($table->comment);
        }

        if ($options !== []) {
            $sql .= ' '.implode(' ', $options);
        }

        return $sql;
    }

    private function columnDefinition(ColumnSchema $column): string
    {
        $parts = [$this->quote($column->name), $column->typeDefinition()];

        $parts[] = $column->nullable ? 'NULL' : 'NOT NULL';

        if ($column->autoIncrement) {
            $parts[] = 'AUTO_INCREMENT';
        }

        if ($column->default !== null) {
            $parts[] = $this->defaultSql($column->default);
        } elseif ($column->nullable && ! $column->autoIncrement) {
            $parts[] = 'DEFAULT NULL';
        }

        if ($column->comment !== null && $column->comment !== '') {
            $parts[] = 'COMMENT '.$this->quoteString($column->comment);
        }

        return implode(' ', $parts);
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function columnDefinitionFromArray(array $data): string
    {
        $name = (string) ($data['name'] ?? 'column');
        $typeDef = (string) ($data['type_definition'] ?? strtoupper((string) ($data['native_type'] ?? 'VARCHAR(255)')));

        $nullableRaw = $data['nullable'] ?? true;
        if (is_bool($nullableRaw)) {
            $nullable = $nullableRaw ? 'NULL' : 'NOT NULL';
        } else {
            $nullable = (string) $nullableRaw;
            if (! in_array(strtoupper($nullable), ['NULL', 'NOT NULL'], true)) {
                $nullable = filter_var($nullableRaw, FILTER_VALIDATE_BOOLEAN) ? 'NULL' : 'NOT NULL';
            }
        }

        $defaultRaw = $data['default'] ?? null;
        if (is_bool($defaultRaw) || is_int($defaultRaw) || is_float($defaultRaw)) {
            $default = $this->defaultSql($defaultRaw);
        } elseif (is_string($defaultRaw)) {
            $default = in_array($defaultRaw, ['DEFAULT NULL', 'NO DEFAULT'], true) || str_starts_with($defaultRaw, 'DEFAULT ')
                ? $defaultRaw
                : $this->defaultSql($defaultRaw);
        } else {
            $default = '';
        }

        $autoIncrement = (bool) ($data['auto_increment'] ?? false);
        $comment = $data['comment'] ?? null;

        $parts = [$this->quote($name), $typeDef, $nullable];

        if ($autoIncrement) {
            $parts[] = 'AUTO_INCREMENT';
        }

        if ($default !== '' && $default !== 'NO DEFAULT') {
            $parts[] = $default;
        }

        if (is_string($comment) && $comment !== '') {
            $parts[] = 'COMMENT '.$this->quoteString($comment);
        }

        return implode(' ', $parts);
    }

    private function buildAddIndexSql(string $table, IndexSchema $index): string
    {
        $cols = implode(', ', array_map(fn ($c) => $this->quote($c), $index->columns));

        return match ($index->type) {
            IndexType::Primary => 'ALTER TABLE '.$this->quote($table).' ADD PRIMARY KEY ('.$cols.')',
            IndexType::Unique => 'ALTER TABLE '.$this->quote($table).' ADD UNIQUE INDEX '.$this->quote($index->name).' ('.$cols.')',
            IndexType::Fulltext => 'ALTER TABLE '.$this->quote($table).' ADD FULLTEXT INDEX '.$this->quote($index->name).' ('.$cols.')',
            IndexType::Spatial => 'ALTER TABLE '.$this->quote($table).' ADD SPATIAL INDEX '.$this->quote($index->name).' ('.$cols.')',
            IndexType::Index => 'ALTER TABLE '.$this->quote($table).' ADD INDEX '.$this->quote($index->name).' ('.$cols.')',
        };
    }

    private function indexInlineDefinition(IndexSchema $index): string
    {
        $cols = implode(', ', array_map(fn ($c) => $this->quote($c), $index->columns));

        return match ($index->type) {
            IndexType::Primary => 'PRIMARY KEY ('.$cols.')',
            IndexType::Unique => 'UNIQUE KEY '.$this->quote($index->name).' ('.$cols.')',
            IndexType::Fulltext => 'FULLTEXT KEY '.$this->quote($index->name).' ('.$cols.')',
            IndexType::Spatial => 'SPATIAL KEY '.$this->quote($index->name).' ('.$cols.')',
            IndexType::Index => 'KEY '.$this->quote($index->name).' ('.$cols.')',
        };
    }

    private function buildAddForeignKeySql(string $table, ForeignKeySchema $fk): string
    {
        $cols = implode(', ', array_map(fn ($c) => $this->quote($c), $fk->columns));
        $refCols = implode(', ', array_map(fn ($c) => $this->quote($c), $fk->referencedColumns));

        return sprintf(
            'ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s) ON DELETE %s ON UPDATE %s',
            $this->quote($table),
            $this->quote($fk->name),
            $cols,
            $this->quote($fk->referencedTable),
            $refCols,
            strtoupper($fk->onDelete),
            strtoupper($fk->onUpdate),
        );
    }

    private function foreignKeyInlineDefinition(ForeignKeySchema $fk): string
    {
        $cols = implode(', ', array_map(fn ($c) => $this->quote($c), $fk->columns));
        $refCols = implode(', ', array_map(fn ($c) => $this->quote($c), $fk->referencedColumns));

        return sprintf(
            'CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s) ON DELETE %s ON UPDATE %s',
            $this->quote($fk->name),
            $cols,
            $this->quote($fk->referencedTable),
            $refCols,
            strtoupper($fk->onDelete),
            strtoupper($fk->onUpdate),
        );
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function hydrateTable(array $data): TableSchema
    {
        $columns = [];
        foreach ($data['columns'] ?? [] as $name => $col) {
            if (! is_array($col)) {
                continue;
            }
            $columns[$name] = new ColumnSchema(
                name: (string) ($col['name'] ?? $name),
                type: (string) ($col['type'] ?? $col['native_type'] ?? 'varchar'),
                nativeType: (string) ($col['native_type'] ?? $col['type'] ?? 'varchar'),
                length: isset($col['length']) ? (int) $col['length'] : null,
                precision: isset($col['precision']) ? (int) $col['precision'] : null,
                scale: isset($col['scale']) ? (int) $col['scale'] : null,
                nullable: (bool) ($col['nullable'] ?? true),
                default: $col['default'] ?? null,
                autoIncrement: (bool) ($col['auto_increment'] ?? false),
                unsigned: (bool) ($col['unsigned'] ?? false),
                comment: isset($col['comment']) ? (string) $col['comment'] : null,
                ordinalPosition: (int) ($col['ordinal_position'] ?? 0),
            );
        }

        $indexes = [];
        foreach ($data['indexes'] ?? [] as $name => $idx) {
            if (! is_array($idx)) {
                continue;
            }
            $indexes[$name] = $this->hydrateIndex($idx);
        }

        $foreignKeys = [];
        foreach ($data['foreign_keys'] ?? [] as $name => $fk) {
            if (! is_array($fk)) {
                continue;
            }
            $foreignKeys[$name] = $this->hydrateForeignKey($fk);
        }

        return new TableSchema(
            name: (string) ($data['name'] ?? 'unknown'),
            columns: $columns,
            indexes: $indexes,
            foreignKeys: $foreignKeys,
            engine: isset($data['engine']) ? (string) $data['engine'] : null,
            charset: isset($data['charset']) ? (string) $data['charset'] : null,
            collation: isset($data['collation']) ? (string) $data['collation'] : null,
            comment: isset($data['comment']) ? (string) $data['comment'] : null,
        );
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function hydrateIndex(array $data): IndexSchema
    {
        $typeValue = (string) ($data['type'] ?? 'index');
        $type = IndexType::tryFrom($typeValue) ?? IndexType::Index;

        return new IndexSchema(
            name: (string) ($data['name'] ?? 'index'),
            type: $type,
            unique: (bool) ($data['unique'] ?? false),
            columns: array_values($data['columns'] ?? []),
        );
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function hydrateForeignKey(array $data): ForeignKeySchema
    {
        return new ForeignKeySchema(
            name: (string) ($data['name'] ?? 'fk'),
            columns: array_values($data['columns'] ?? []),
            referencedTable: (string) ($data['referenced_table'] ?? ''),
            referencedColumns: array_values($data['referenced_columns'] ?? []),
            onDelete: (string) ($data['on_delete'] ?? 'RESTRICT'),
            onUpdate: (string) ($data['on_update'] ?? 'RESTRICT'),
        );
    }

    private function defaultSql(mixed $default): string
    {
        if ($default === null) {
            return 'DEFAULT NULL';
        }

        if (is_string($default) && strtoupper($default) === 'CURRENT_TIMESTAMP') {
            return 'DEFAULT CURRENT_TIMESTAMP';
        }

        if (is_bool($default)) {
            return 'DEFAULT '.($default ? '1' : '0');
        }

        if (is_int($default) || is_float($default)) {
            return 'DEFAULT '.$default;
        }

        return 'DEFAULT '.$this->quoteString((string) $default);
    }

    /**
     * Prefer non-destructive first, destructive last; keep relative order within groups.
     *
     * @param  list<SqlStatement>  $statements
     * @return list<SqlStatement>
     */
    private function orderStatements(array $statements): array
    {
        $safe = [];
        $destructive = [];

        foreach ($statements as $statement) {
            if ($statement->destructive) {
                $destructive[] = $statement;
            } else {
                $safe[] = $statement;
            }
        }

        return array_merge($safe, $destructive);
    }

    private function quote(string $identifier): string
    {
        return '`'.str_replace('`', '``', $identifier).'`';
    }

    private function quoteString(string $value): string
    {
        return "'".str_replace(["\\", "'"], ["\\\\", "\\'"], $value)."'";
    }
}
