<?php

declare(strict_types=1);

namespace SchemaLens\Tests\Unit;

use SchemaLens\Comparison\SchemaComparator;
use SchemaLens\DTO\ColumnSchema;
use SchemaLens\DTO\DatabaseSchema;
use SchemaLens\DTO\TableSchema;
use SchemaLens\Migration\MigrationGenerator;
use SchemaLens\Tests\TestCase;

final class MigrationGeneratorTest extends TestCase
{
    public function test_generates_migration_file_with_review_warning(): void
    {
        $from = new DatabaseSchema('mysql', 'mysql', 'a', [
            'widgets' => new TableSchema('widgets', [
                'id' => new ColumnSchema('id', 'int', 'int', nullable: false, ordinalPosition: 1),
            ]),
        ]);
        $to = new DatabaseSchema('production', 'mysql', 'b', []);

        $result = (new SchemaComparator)->compare($from, $to);
        $dir = sys_get_temp_dir().DIRECTORY_SEPARATOR.'schemalens_migrations_'.uniqid();
        $path = (new MigrationGenerator)->generate($result, $dir);

        $this->assertFileExists($path);
        $contents = (string) file_get_contents($path);

        $this->assertStringContainsString('Generated by SchemaLens', $contents);
        $this->assertStringContainsString('Review this migration carefully', $contents);
        $this->assertStringContainsString('does not automatically execute', $contents);
        $this->assertStringContainsString('CREATE TABLE', $contents);
        $this->assertStringContainsString('function down()', $contents);

        @unlink($path);
        @rmdir($dir);
    }
}
