<?php

declare(strict_types=1);

namespace SchemaLens\Tests\Unit;

use SchemaLens\Comparison\SchemaComparator;
use SchemaLens\DTO\ColumnSchema;
use SchemaLens\DTO\DatabaseSchema;
use SchemaLens\DTO\TableSchema;
use SchemaLens\Sql\SqlGenerator;
use SchemaLens\Support\CredentialSanitizer;
use SchemaLens\Support\Normalization\SchemaNormalizer;
use SchemaLens\Tests\TestCase;

final class SqlGeneratorAndSecurityTest extends TestCase
{
    public function test_generates_alter_modify_and_marks_destructive_drops(): void
    {
        $from = new DatabaseSchema('mysql', 'mysql', 'a', [
            'special_permissions' => new TableSchema('special_permissions', [
                'status' => new ColumnSchema('status', 'varchar', 'varchar', length: 255, nullable: true, ordinalPosition: 1),
                'keep' => new ColumnSchema('keep', 'int', 'int', nullable: false, ordinalPosition: 2),
            ]),
            'only_source' => new TableSchema('only_source', [
                'id' => new ColumnSchema('id', 'int', 'int', nullable: false, ordinalPosition: 1),
            ]),
        ]);

        $to = new DatabaseSchema('production', 'mysql', 'b', [
            'special_permissions' => new TableSchema('special_permissions', [
                'status' => new ColumnSchema('status', 'varchar', 'varchar', length: 100, nullable: false, ordinalPosition: 1),
                'keep' => new ColumnSchema('keep', 'int', 'int', nullable: false, ordinalPosition: 2),
                'extra_col' => new ColumnSchema('extra_col', 'int', 'int', nullable: true, ordinalPosition: 3),
            ]),
            'only_target' => new TableSchema('only_target', [
                'id' => new ColumnSchema('id', 'int', 'int', nullable: false, ordinalPosition: 1),
            ]),
        ]);

        $result = (new SchemaComparator)->compare($from, $to);
        $statements = (new SqlGenerator)->generate($result);

        $sql = implode("\n", array_map(fn ($s) => $s->sql, $statements));

        $this->assertStringContainsString('MODIFY COLUMN', $sql);
        $this->assertStringContainsString('`status`', $sql);
        $this->assertStringContainsString('VARCHAR(255)', $sql);
        $this->assertStringContainsString('CREATE TABLE', $sql);
        $this->assertStringContainsString('DROP TABLE', $sql);
        $this->assertStringContainsString('DROP COLUMN', $sql);

        $destructive = array_filter($statements, fn ($s) => $s->destructive);
        $this->assertNotEmpty($destructive);
    }

    public function test_sql_string_includes_safety_header(): void
    {
        $from = new DatabaseSchema('mysql', 'mysql', 'a', [
            't' => new TableSchema('t', [
                'a' => new ColumnSchema('a', 'int', 'int', nullable: false, ordinalPosition: 1),
            ]),
        ]);
        $to = new DatabaseSchema('production', 'mysql', 'b', []);

        $result = (new SchemaComparator)->compare($from, $to);
        $text = (new SqlGenerator)->toSqlString($result);

        $this->assertStringContainsString('Generated by SchemaLens', $text);
        $this->assertStringContainsString('does NOT execute', $text);
    }

    public function test_credential_sanitizer_strips_passwords(): void
    {
        $dirty = 'mysql://user:super-secret-password-do-not-leak@10.0.0.5/db password=hunter2';
        $clean = CredentialSanitizer::sanitize($dirty);

        $this->assertStringNotContainsString('super-secret-password-do-not-leak', $clean);
        $this->assertStringNotContainsString('hunter2', $clean);
        $this->assertStringContainsString('***', $clean);
    }

    public function test_sanitize_array_removes_password_keys(): void
    {
        $clean = CredentialSanitizer::sanitizeArray([
            'connection' => 'production',
            'password' => 'secret',
            'nested' => ['pwd' => 'x', 'database' => 'app'],
        ]);

        $this->assertArrayNotHasKey('password', $clean);
        $this->assertArrayNotHasKey('pwd', $clean['nested']);
        $this->assertSame('app', $clean['nested']['database']);
    }

    public function test_normalizer_equates_equivalent_defaults(): void
    {
        $this->assertTrue(SchemaNormalizer::defaultsEqual('0', 0, 'int'));
        $this->assertTrue(SchemaNormalizer::defaultsEqual('CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP', 'timestamp'));
        $this->assertTrue(SchemaNormalizer::defaultsEqual(null, 'NULL', 'varchar'));
        $this->assertSame('int', SchemaNormalizer::normalizeType('integer'));
        $this->assertSame('RESTRICT', SchemaNormalizer::normalizeAction('NO ACTION'));
    }

    public function test_json_report_never_includes_password(): void
    {
        $from = new DatabaseSchema('production', 'mysql', 'app_production', [], host: '10.0.0.5');
        $to = new DatabaseSchema('mysql', 'mysql', 'app_local', []);
        $result = (new SchemaComparator)->compare($from, $to);

        $json = (new \SchemaLens\Reports\JsonReport)->export($result);

        $this->assertStringNotContainsString('super-secret-password-do-not-leak', $json);
        $this->assertStringNotContainsString('"password"', $json);
    }
}
